// 在线动漫源规则 (XPath 选择器来自 Kazumi 项目)
const YIDIAN_RULE = {
  name: '樱花动漫',
  baseURL: 'http://yidian68.com',
  searchURL: 'http://yidian68.com/search.php?searchword=@keyword',
  useWebview: true,
  homeSections: '.myui-panel',
  homeTitle: '.myui-panel__head .title',
  homeMore: '.myui-panel__head .more',
  homeItems: '.myui-vodlist__box',
  searchList: '.myui-vodlist__box',
  searchName: '.myui-vodlist__thumb',
  searchNameAttr: 'title',
  searchResult: '.myui-vodlist__thumb',
  searchResultAttr: 'href',
  searchCover: '',
  searchCoverAttr: 'data-original',
  searchTag: '.pic-tag',
  searchEpisode: '.pic-text',
  detailTitle: '.myui-player__detail h1',
  detailCover: '.myui-vodlist__thumb.img-md-220 img',
  detailCoverAttr: 'data-original',
  detailDesc: '.myui-content__detail .text',
  chapterRoads: '.tab-pane',
  chapterRoadNames: '.nav-tabs li a',
  chapterResult: '.myui-content__list li a',
  chapterNameAttr: 'title',
  chapterUrlAttr: 'href',
  playUrlRegex: 'var\\s+now\\s*=\\s*["\']([^"\']+)["\']',
}

const KAZUMI_RULES = [
  {
    name: '风铃动漫',
    baseURL: 'https://www.aafun.cc/',
    searchURL: 'https://www.aafun.cc/feng-s.html?wd=@keyword&submit=',
    useWebview: false,
    // 首页（CSS - conch 模板）
    homeSections: '.hl-row-box',
    homeTitle: 'h2.hl-rb-title',
    homeMore: 'a.hl-rb-more',
    homeItems: 'li.hl-list-item',
    // 搜索（CSS - conch 模板）
    searchList: 'li.hl-list-item',
    searchName: 'a.hl-item-thumb',
    searchNameAttr: 'title',
    searchResult: 'a.hl-item-thumb',
    searchResultAttr: 'href',
    searchCover: 'a.hl-item-thumb',
    searchCoverAttr: 'data-original',
    searchTag: '.hl-pic-tag span',
    searchEpisode: '.hl-pic-text .remarks',
    // 详情（CSS）
    detailTitle: 'title',
    detailCover: 'a.hl-item-thumb',
    detailCoverAttr: 'data-original',
    detailDesc: '.hl-item-sub.hl-text-muted',
    // 剧集（CSS - conch 模板）
    chapterRoads: '.hl-plays-list',
    chapterRoadNames: '.hl-plays-from a',
    chapterResult: 'li a',
    chapterNameAttr: 'title',
    chapterUrlAttr: 'href',
    playUrlRegex: '',
  },
  {
    name: 'AGE动漫',
    baseURL: 'https://www.agedm.io/',
    searchURL: 'https://www.agedm.io/search?query=@keyword',
    useWebview: true,
    // 首页（无首页功能）
    homeSections: '',
    // 搜索（XPath，来自 Kazumi AGE.json）
    searchList: '//div[2]/div/section/div/div/div/div',
    searchName: './/div/div[2]/h5/a',
    searchNameAttr: '',
    searchResult: './/div/div[2]/h5/a',
    searchResultAttr: 'href',
    searchCover: './/img',
    searchCoverAttr: 'data-src',
    searchTag: '',
    searchEpisode: '',
    // 详情
    detailTitle: 'title',
    detailCover: '.video-cover img',
    detailCoverAttr: 'data-src',
    detailDesc: '.video-info .desc',
    // 剧集（XPath，来自 Kazumi AGE.json）
    chapterRoads: '//div[2]/div/section/div/div[2]/div[2]/div[2]/div',
    chapterRoadNames: '',
    chapterResult: './/ul/li/a',
    chapterNameAttr: '',
    chapterUrlAttr: 'href',
    playUrlRegex: '',
  },
  {
    name: '动漫巴士',
    baseURL: 'https://dmbus.cc/',
    searchURL: 'https://dmbus.cc/s----------.html?wd=@keyword',
    useWebview: true,
    // 首页（无首页功能）
    homeSections: '',
    // 搜索（XPath，来自 Kazumi DM84.json）
    searchList: '//div/div[3]/ul/li',
    searchName: './/div/a[2]',
    searchNameAttr: '',
    searchResult: './/div/a[2]',
    searchResultAttr: 'href',
    searchCover: './/img',
    searchCoverAttr: 'data-original',
    searchTag: '',
    searchEpisode: '',
    // 详情
    detailTitle: 'title',
    detailCover: '.video-cover img',
    detailCoverAttr: 'data-original',
    detailDesc: '.video-detail .text',
    // 剧集（XPath，来自 Kazumi DM84.json）
    chapterRoads: '//div/div[4]/div/ul',
    chapterRoadNames: '',
    chapterResult: './/li/a',
    chapterNameAttr: '',
    chapterUrlAttr: 'href',
    playUrlRegex: '',
  },
]

module.exports = { YIDIAN_RULE, KAZUMI_RULES }
